name: Feature Request
description: Please submit feature requests as a Discussion.
labels: []
body:
    - type: markdown
      attributes:
          value: |
              ## Feature Requests have moved to Discussions
              Please [submit feature requests as Discussions](https://github.com/davish/obsidian-full-calendar/discussions/new?category=feature-requests) so that they can be voted on and prioritized.
